import { Job, Submission, Payment, DashboardStats, User } from './types'

// Mock user
export const mockUser: User = {
  id: '1',
  email: 'official@GreenTask.in',
  name: 'Rajesh Kumar',
  role: 'official',
  gramPanchayat: 'Rampur',
  district: 'Varanasi',
  state: 'Uttar Pradesh',
}

// Mock jobs
export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Plant 100 Trees in Village Commons',
    description: 'Plant native tree species in the village common area to increase green cover and combat climate change.',
    category: 'Tree Planting',
    location: 'Rampur Village, Varanasi',
    latitude: 25.3176,
    longitude: 82.9739,
    rewardAmount: 5000,
    deadline: '2024-12-31',
    proofRequirements: 'Before and after photos with geotag, photos of planted saplings with identification tags',
    status: 'open',
    createdBy: '1',
    createdAt: '2024-11-01T10:00:00Z',
    applications: [
      {
        id: 'app1',
        jobId: '1',
        applicantId: 'worker1',
        applicantName: 'Suresh Yadav',
        applicantPhone: '+91 9876543210',
        appliedAt: '2024-11-02T09:00:00Z',
        status: 'pending',
      },
      {
        id: 'app2',
        jobId: '1',
        applicantId: 'worker2',
        applicantName: 'Priya Sharma',
        applicantPhone: '+91 9876543211',
        appliedAt: '2024-11-02T11:00:00Z',
        status: 'pending',
      },
    ],
  },
  {
    id: '2',
    title: 'Install Rainwater Harvesting System',
    description: 'Set up a community rainwater harvesting system to conserve water during monsoon season.',
    category: 'Water Harvesting',
    location: 'Community Center, Rampur',
    latitude: 25.3180,
    longitude: 82.9745,
    rewardAmount: 8000,
    deadline: '2024-11-30',
    proofRequirements: 'Installation photos, water storage capacity measurement, geotag verification',
    status: 'assigned',
    createdBy: '1',
    createdAt: '2024-10-15T10:00:00Z',
    assignedTo: 'worker3',
    assignedAt: '2024-10-20T14:00:00Z',
  },
  {
    id: '3',
    title: 'Solar Panel Maintenance - School Building',
    description: 'Clean and maintain solar panels installed on the primary school roof.',
    category: 'Solar Maintenance',
    location: 'Primary School, Rampur',
    latitude: 25.3185,
    longitude: 82.9750,
    rewardAmount: 3000,
    deadline: '2024-11-20',
    proofRequirements: 'Before/after cleaning photos, efficiency report, geotag',
    status: 'under_review',
    createdBy: '1',
    createdAt: '2024-10-01T10:00:00Z',
    assignedTo: 'worker4',
    assignedAt: '2024-10-05T10:00:00Z',
  },
  {
    id: '4',
    title: 'Waste Segregation Drive',
    description: 'Organize and execute a waste segregation drive in the village, set up collection points.',
    category: 'Waste Management',
    location: 'Rampur Village',
    latitude: 25.3170,
    longitude: 82.9735,
    rewardAmount: 4000,
    deadline: '2024-12-15',
    proofRequirements: 'Photos of collection points, waste segregation documentation, community participation photos',
    status: 'completed',
    createdBy: '1',
    createdAt: '2024-09-01T10:00:00Z',
    assignedTo: 'worker5',
    assignedAt: '2024-09-05T10:00:00Z',
  },
]

// Mock submissions
export const mockSubmissions: Submission[] = [
  {
    id: 'sub1',
    jobId: '3',
    job: mockJobs[2],
    workerId: 'worker4',
    workerName: 'Amit Verma',
    workerPhone: '+91 9876543213',
    submittedAt: '2024-11-08T15:30:00Z',
    beforePhoto: '/images/before1.jpg',
    afterPhoto: '/images/after1.jpg',
    geotagVerified: true,
    latitude: 25.3185,
    longitude: 82.9750,
    notes: 'All solar panels cleaned and inspected. Efficiency improved by 15%.',
    status: 'pending',
  },
  {
    id: 'sub2',
    jobId: '2',
    job: mockJobs[1],
    workerId: 'worker3',
    workerName: 'Ramesh Singh',
    workerPhone: '+91 9876543212',
    submittedAt: '2024-11-07T12:00:00Z',
    beforePhoto: '/images/before2.jpg',
    afterPhoto: '/images/after2.jpg',
    geotagVerified: true,
    latitude: 25.3180,
    longitude: 82.9745,
    notes: 'Rainwater harvesting system installed with 5000L capacity.',
    status: 'pending',
  },
]

// Mock payments
export const mockPayments: Payment[] = [
  {
    id: 'pay1',
    jobId: '4',
    jobTitle: 'Waste Segregation Drive',
    workerId: 'worker5',
    workerName: 'Sunita Devi',
    amount: 4000,
    status: 'paid',
    submittedAt: '2024-09-20T10:00:00Z',
    approvedAt: '2024-09-22T14:00:00Z',
    paidAt: '2024-09-25T10:00:00Z',
    approvedBy: '1',
  },
  {
    id: 'pay2',
    jobId: '3',
    jobTitle: 'Solar Panel Maintenance - School Building',
    workerId: 'worker4',
    workerName: 'Amit Verma',
    amount: 3000,
    status: 'pending_approval',
    submittedAt: '2024-11-08T15:30:00Z',
  },
  {
    id: 'pay3',
    jobId: '2',
    jobTitle: 'Install Rainwater Harvesting System',
    workerId: 'worker3',
    workerName: 'Ramesh Singh',
    amount: 8000,
    status: 'approved',
    submittedAt: '2024-11-07T12:00:00Z',
    approvedAt: '2024-11-08T10:00:00Z',
    approvedBy: '1',
  },
]

// Mock dashboard stats
export const mockDashboardStats: DashboardStats = {
  totalJobsPosted: 12,
  activeJobs: 5,
  pendingVerifications: 2,
  totalAmountDistributed: 45000,
  treesPlanted: 450,
  co2Offset: 2250,
}
